[package]
name = "s3wf2-wasm"
version = "0.1.0"
authors = ["Yuu Kobayashi <kb10uy@kb10uy.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.regex]
version = "1.3"
features = ["std", "perf", "unicode-perl"]
