name: Build and test s3wf2-rs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      working-directory: ./packages/s3wf2-rs
      run: cargo build --path ./packages/s3wf2-rs --verbose
    - name: Run tests
      working-directory: ./packages/s3wf2-rs
      run: cargo test --path ./packages/s3wf2-rs --verbose
